server:
  port: 8080

spring:
  jpa:
    open-in-view: true
  application:
    name: camel-rest
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elidSetAutoCommits: true
        maintainTimeStats: false
